# Generated by Django 5.1.5 on 2025-01-19 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='content',
            field=models.TextField(default='Write your text here...'),
        ),
        migrations.AddField(
            model_name='entry',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
