# Generated by Django 5.1.5 on 2025-01-20 08:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0002_entry_content_entry_date_created_entry_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
