# Generated by Django 5.1.5 on 2025-01-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0003_alter_entry_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(default='Write text here...'),
        ),
    ]
