# Generated by Django 5.1.5 on 2025-01-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0004_alter_entry_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
