# Generated by Django 5.1.5 on 2025-01-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textentry',
            name='content',
        ),
    ]
