# Generated by Django 5.1.5 on 2025-01-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0007_remove_textentry_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='textentry',
            name='content',
            field=models.TextField(default='Write text here...'),
        ),
    ]
